/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/new-chat`; params?: Router.UnknownInputParams; } | { pathname: `/new-ride`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/clubs` | `/clubs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/riders` | `/riders`; params?: Router.UnknownInputParams; } | { pathname: `/strava/connect`; params?: Router.UnknownInputParams; } | { pathname: `/chat/[roomId]`, params: Router.UnknownInputParams & { roomId: string | number; } } | { pathname: `/club/[clubId]`, params: Router.UnknownInputParams & { clubId: string | number; } } | { pathname: `/ride/[rideId]`, params: Router.UnknownInputParams & { rideId: string | number; } } | { pathname: `/edit-chat/[roomId]`, params: Router.UnknownInputParams & { roomId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/new-chat`; params?: Router.UnknownOutputParams; } | { pathname: `/new-ride`; params?: Router.UnknownOutputParams; } | { pathname: `/notifications`; params?: Router.UnknownOutputParams; } | { pathname: `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/clubs` | `/clubs`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/riders` | `/riders`; params?: Router.UnknownOutputParams; } | { pathname: `/strava/connect`; params?: Router.UnknownOutputParams; } | { pathname: `/chat/[roomId]`, params: Router.UnknownOutputParams & { roomId: string; } } | { pathname: `/club/[clubId]`, params: Router.UnknownOutputParams & { clubId: string; } } | { pathname: `/ride/[rideId]`, params: Router.UnknownOutputParams & { rideId: string; } } | { pathname: `/edit-chat/[roomId]`, params: Router.UnknownOutputParams & { roomId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/new-chat${`?${string}` | `#${string}` | ''}` | `/new-ride${`?${string}` | `#${string}` | ''}` | `/notifications${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chats${`?${string}` | `#${string}` | ''}` | `/chats${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/clubs${`?${string}` | `#${string}` | ''}` | `/clubs${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/riders${`?${string}` | `#${string}` | ''}` | `/riders${`?${string}` | `#${string}` | ''}` | `/strava/connect${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/new-chat`; params?: Router.UnknownInputParams; } | { pathname: `/new-ride`; params?: Router.UnknownInputParams; } | { pathname: `/notifications`; params?: Router.UnknownInputParams; } | { pathname: `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup` | `/signup`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chats` | `/chats`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/clubs` | `/clubs`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/riders` | `/riders`; params?: Router.UnknownInputParams; } | { pathname: `/strava/connect`; params?: Router.UnknownInputParams; } | `/chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/club/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/ride/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/edit-chat/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/chat/[roomId]`, params: Router.UnknownInputParams & { roomId: string | number; } } | { pathname: `/club/[clubId]`, params: Router.UnknownInputParams & { clubId: string | number; } } | { pathname: `/ride/[rideId]`, params: Router.UnknownInputParams & { rideId: string | number; } } | { pathname: `/edit-chat/[roomId]`, params: Router.UnknownInputParams & { roomId: string | number; } };
    }
  }
}
